name = "taxiautorizadolima"
compatibility_date = "2025-08-27"

[build]
upload = { dir = "./dist" }

[assets]
directory = "./dist"

[env.production]
route = "www.taxiautorizadolima.com/*"
zone_id = "6b77c94d500cc53ddbcf2de77149b190"
